[clients]
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com
192.168.2.126 user=pradeep pass=vinove email=yash.bansal@mail.vinove.com

