[workstatus_clients]
192.168.2.216 ansible_user="yash" ansible_password="vinove" os=windows email=arshvisible1@yopmail.com


[workstatus_clients:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore